CREATE DATABASE IF NOT EXISTS origin_db;

CREATE TABLE IF NOT EXISTS origin_db.users (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    year YEAR NOT NULL,
    create_date DATETIME DEFAULT CURRENT_TIMESTAMP
);