CREATE TABLE IF NOT EXISTS users (
    ID SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    year INT CHECK (year BETWEEN 1000 AND 9999),
    create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    migrate_date TIMESTAMP
);